name: Build OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (config)
        uses: actions/checkout@v2

      - name: Clone OpenWrt source code
        run: |
          git clone --depth=1 https://github.com/coolsnowwolf/lede openwrt

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools \
          rsync unzip zlib1g-dev file wget libelf-dev ecj fastjar java-propose-classpath

      - name: Initialize feeds and install packages
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load default config and download sources
        run: |
          cd openwrt
          cp ../.config .config
          make defconfig
          make -j$(nproc) download

      - name: Build OpenWrt
        run: |
          cd openwrt
          make -j$(nproc) V=s
